<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="6" total="17" passed="1" failed="10" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-07-20T18:31:15 IST" name="Suite" finished-at="2023-07-20T18:31:17 IST" duration-ms="1556">
    <groups>
      <group name="SetupVAS">
        <method signature="TC_ProcedurePageTest.addProcedureToAttachFileForReference()[pri:4, instance:com.VMS.TestCases.TC_ProcedurePageTest@5db99216]" name="addProcedureToAttachFileForReference" class="com.VMS.TestCases.TC_ProcedurePageTest"/>
        <method signature="TC_ProcedurePageTest.addProcedureToOpenNextActionAfterAck()[pri:3, instance:com.VMS.TestCases.TC_ProcedurePageTest@5db99216]" name="addProcedureToOpenNextActionAfterAck" class="com.VMS.TestCases.TC_ProcedurePageTest"/>
        <method signature="TC_ProcedurePageTest.addProcedureUserMustCommentToAcknowledge()[pri:2, instance:com.VMS.TestCases.TC_ProcedurePageTest@5db99216]" name="addProcedureUserMustCommentToAcknowledge" class="com.VMS.TestCases.TC_ProcedurePageTest"/>
      </group> <!-- SetupVAS -->
      <group name="Setup">
        <method signature="TC_NetworkingPageTest.enableVAXTab()[pri:0, instance:com.VMS.TestCases.TC_NetworkingPageTest@5c1bd44c]" name="enableVAXTab" class="com.VMS.TestCases.TC_NetworkingPageTest"/>
        <method signature="TC_NetworkingPageTest.verifyIntegratedVAX()[pri:1, instance:com.VMS.TestCases.TC_NetworkingPageTest@5c1bd44c]" name="verifyIntegratedVAX" class="com.VMS.TestCases.TC_NetworkingPageTest"/>
        <method signature="TC_ProcedurePageTest.addProcedureToAcknowledge()[pri:1, instance:com.VMS.TestCases.TC_ProcedurePageTest@5db99216]" name="addProcedureToAcknowledge" class="com.VMS.TestCases.TC_ProcedurePageTest"/>
        <method signature="TC_ProcedurePageTest.addProcedureToAttachFileForReference()[pri:4, instance:com.VMS.TestCases.TC_ProcedurePageTest@5db99216]" name="addProcedureToAttachFileForReference" class="com.VMS.TestCases.TC_ProcedurePageTest"/>
        <method signature="TC_ProcedurePageTest.addProcedureToOpenNextActionAfterAck()[pri:3, instance:com.VMS.TestCases.TC_ProcedurePageTest@5db99216]" name="addProcedureToOpenNextActionAfterAck" class="com.VMS.TestCases.TC_ProcedurePageTest"/>
        <method signature="TC_ProcedurePageTest.addProcedureUserMustCommentToAcknowledge()[pri:2, instance:com.VMS.TestCases.TC_ProcedurePageTest@5db99216]" name="addProcedureUserMustCommentToAcknowledge" class="com.VMS.TestCases.TC_ProcedurePageTest"/>
      </group> <!-- Setup -->
      <group name="SetupVAX">
        <method signature="TC_NetworkingPageTest.enableVAXTab()[pri:0, instance:com.VMS.TestCases.TC_NetworkingPageTest@5c1bd44c]" name="enableVAXTab" class="com.VMS.TestCases.TC_NetworkingPageTest"/>
        <method signature="TC_ProcedurePageTest.addProcedureToAttachFileForReference()[pri:4, instance:com.VMS.TestCases.TC_ProcedurePageTest@5db99216]" name="addProcedureToAttachFileForReference" class="com.VMS.TestCases.TC_ProcedurePageTest"/>
        <method signature="TC_ProcedurePageTest.addProcedureToOpenNextActionAfterAck()[pri:3, instance:com.VMS.TestCases.TC_ProcedurePageTest@5db99216]" name="addProcedureToOpenNextActionAfterAck" class="com.VMS.TestCases.TC_ProcedurePageTest"/>
        <method signature="TC_ProcedurePageTest.addProcedureUserMustCommentToAcknowledge()[pri:2, instance:com.VMS.TestCases.TC_ProcedurePageTest@5db99216]" name="addProcedureUserMustCommentToAcknowledge" class="com.VMS.TestCases.TC_ProcedurePageTest"/>
      </group> <!-- SetupVAX -->
    </groups>
    <test started-at="2023-07-20T18:31:15 IST" name="OldVMSVersionSetup(BeforeUpgrade)" finished-at="2023-07-20T18:31:17 IST" duration-ms="1556">
      <class name="com.VMS.TestCases.TC_NetworkingPageTest">
        <test-method signature="enableVAXTab()[pri:0, instance:com.VMS.TestCases.TC_NetworkingPageTest@5c1bd44c]" started-at="2023-07-20T18:31:17 IST" name="enableVAXTab" finished-at="2023-07-20T18:31:17 IST" duration-ms="1" status="FAIL">
          <exception class="java.lang.NullPointerException">
            <message>
              <![CDATA[Cannot invoke "com.VMS.PageObject.vms_NetworkingPage.verifyVAXtabIsEnabled()" because "this.networking" is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException: Cannot invoke "com.VMS.PageObject.vms_NetworkingPage.verifyVAXtabIsEnabled()" because "this.networking" is null
at com.VMS.TestCases.TC_NetworkingPageTest.enableVAXTab(TC_NetworkingPageTest.java:10)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- enableVAXTab -->
        <test-method signature="verifyIntegratedVAX()[pri:1, instance:com.VMS.TestCases.TC_NetworkingPageTest@5c1bd44c]" started-at="2023-07-20T18:31:17 IST" name="verifyIntegratedVAX" finished-at="2023-07-20T18:31:17 IST" duration-ms="2" status="FAIL">
          <exception class="java.lang.NullPointerException">
            <message>
              <![CDATA[Cannot invoke "com.VMS.PageObject.vms_NetworkingPage.verifyConfiguredVAX()" because "this.networking" is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException: Cannot invoke "com.VMS.PageObject.vms_NetworkingPage.verifyConfiguredVAX()" because "this.networking" is null
at com.VMS.TestCases.TC_NetworkingPageTest.verifyIntegratedVAX(TC_NetworkingPageTest.java:27)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyIntegratedVAX -->
      </class> <!-- com.VMS.TestCases.TC_NetworkingPageTest -->
      <class name="com.VMS.TestCases.TC_WebPagesTest">
        <test-method is-config="true" signature="setup()[pri:0, instance:com.VMS.TestCases.TC_WebPagesTest@4da855dd]" started-at="2023-07-20T18:31:07 IST" name="setup" finished-at="2023-07-20T18:31:15 IST" duration-ms="8432" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="OpenWebPages()[pri:0, instance:com.VMS.TestCases.TC_WebPagesTest@4da855dd]" started-at="2023-07-20T18:31:16 IST" name="OpenWebPages" finished-at="2023-07-20T18:31:17 IST" duration-ms="1223" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- OpenWebPages -->
        <test-method signature="addAllWebpage()[pri:0, instance:com.VMS.TestCases.TC_WebPagesTest@4da855dd]" started-at="2023-07-20T18:31:17 IST" name="addAllWebpage" finished-at="2023-07-20T18:31:17 IST" duration-ms="45" status="FAIL">
          <exception class="java.lang.NullPointerException">
            <message>
              <![CDATA[Cannot invoke "java.io.InputStream.markSupported()" because "stream" is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException: Cannot invoke "java.io.InputStream.markSupported()" because "stream" is null
at org.apache.poi.poifs.filesystem.FileMagic.prepareToCheckMagic(FileMagic.java:222)
at org.apache.poi.openxml4j.opc.internal.ZipHelper.openZipStream(ZipHelper.java:174)
at org.apache.poi.openxml4j.opc.ZipPackage.<init>(ZipPackage.java:130)
at org.apache.poi.openxml4j.opc.OPCPackage.open(OPCPackage.java:319)
at org.apache.poi.ooxml.util.PackageHelper.open(PackageHelper.java:59)
at org.apache.poi.xssf.usermodel.XSSFWorkbook.<init>(XSSFWorkbook.java:290)
at org.apache.poi.xssf.usermodel.XSSFWorkbook.<init>(XSSFWorkbook.java:286)
at com.VMS.TestCases.TC_WebPagesTest.addAllWebpage(TC_WebPagesTest.java:84)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addAllWebpage -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.VMS.TestCases.TC_WebPagesTest@4da855dd]" started-at="2023-07-20T18:31:17 IST" name="tearDown" finished-at="2023-07-20T18:31:18 IST" duration-ms="339" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.VMS.TestCases.TC_WebPagesTest -->
      <class name="com.VMS.TestCases.TC_ProcedurePageTest">
        <test-method signature="OpenProcedurePage()[pri:0, instance:com.VMS.TestCases.TC_ProcedurePageTest@5db99216]" started-at="2023-07-20T18:31:17 IST" name="OpenProcedurePage" finished-at="2023-07-20T18:31:17 IST" duration-ms="1" status="FAIL">
          <exception class="java.lang.NullPointerException">
            <message>
              <![CDATA[Cannot invoke "com.VMS.PageObject.vms_ProcedurePage.openProdecurepage()" because "this.procedure" is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException: Cannot invoke "com.VMS.PageObject.vms_ProcedurePage.openProdecurepage()" because "this.procedure" is null
at com.VMS.TestCases.TC_ProcedurePageTest.OpenProcedurePage(TC_ProcedurePageTest.java:11)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- OpenProcedurePage -->
        <test-method signature="addProcedureToAcknowledge()[pri:1, instance:com.VMS.TestCases.TC_ProcedurePageTest@5db99216]" started-at="2023-07-20T18:31:17 IST" name="addProcedureToAcknowledge" finished-at="2023-07-20T18:31:17 IST" duration-ms="1" status="FAIL">
          <exception class="java.lang.NullPointerException">
            <message>
              <![CDATA[Cannot invoke "com.VMS.PageObject.vms_ProcedurePage.clickOnNEWbtn()" because "this.procedure" is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException: Cannot invoke "com.VMS.PageObject.vms_ProcedurePage.clickOnNEWbtn()" because "this.procedure" is null
at com.VMS.TestCases.TC_ProcedurePageTest.addProcedureToAcknowledge(TC_ProcedurePageTest.java:18)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addProcedureToAcknowledge -->
        <test-method signature="addProcedureUserMustCommentToAcknowledge()[pri:2, instance:com.VMS.TestCases.TC_ProcedurePageTest@5db99216]" started-at="2023-07-20T18:31:17 IST" name="addProcedureUserMustCommentToAcknowledge" finished-at="2023-07-20T18:31:17 IST" duration-ms="2" status="FAIL">
          <exception class="java.lang.NullPointerException">
            <message>
              <![CDATA[Cannot invoke "com.VMS.PageObject.vms_ProcedurePage.clickOnNEWbtn()" because "this.procedure" is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException: Cannot invoke "com.VMS.PageObject.vms_ProcedurePage.clickOnNEWbtn()" because "this.procedure" is null
at com.VMS.TestCases.TC_ProcedurePageTest.addProcedureUserMustCommentToAcknowledge(TC_ProcedurePageTest.java:27)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addProcedureUserMustCommentToAcknowledge -->
        <test-method signature="addProcedureToOpenNextActionAfterAck()[pri:3, instance:com.VMS.TestCases.TC_ProcedurePageTest@5db99216]" started-at="2023-07-20T18:31:17 IST" name="addProcedureToOpenNextActionAfterAck" finished-at="2023-07-20T18:31:17 IST" duration-ms="1" status="FAIL">
          <exception class="java.lang.NullPointerException">
            <message>
              <![CDATA[Cannot invoke "com.VMS.PageObject.vms_ProcedurePage.clickOnNEWbtn()" because "this.procedure" is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException: Cannot invoke "com.VMS.PageObject.vms_ProcedurePage.clickOnNEWbtn()" because "this.procedure" is null
at com.VMS.TestCases.TC_ProcedurePageTest.addProcedureToOpenNextActionAfterAck(TC_ProcedurePageTest.java:38)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addProcedureToOpenNextActionAfterAck -->
        <test-method signature="addProcedureToAttachFileForReference()[pri:4, instance:com.VMS.TestCases.TC_ProcedurePageTest@5db99216]" started-at="2023-07-20T18:31:17 IST" name="addProcedureToAttachFileForReference" finished-at="2023-07-20T18:31:17 IST" duration-ms="2" status="FAIL">
          <exception class="java.lang.NullPointerException">
            <message>
              <![CDATA[Cannot invoke "com.VMS.PageObject.vms_ProcedurePage.clickOnNEWbtn()" because "this.procedure" is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException: Cannot invoke "com.VMS.PageObject.vms_ProcedurePage.clickOnNEWbtn()" because "this.procedure" is null
at com.VMS.TestCases.TC_ProcedurePageTest.addProcedureToAttachFileForReference(TC_ProcedurePageTest.java:50)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addProcedureToAttachFileForReference -->
      </class> <!-- com.VMS.TestCases.TC_ProcedurePageTest -->
      <class name="com.VMS.TestCases.TC_MapTest">
        <test-method signature="addNewMap()[pri:1, instance:com.VMS.TestCases.TC_MapTest@3ec11999]" started-at="2023-07-20T18:31:17 IST" name="addNewMap" finished-at="2023-07-20T18:31:17 IST" duration-ms="1" status="FAIL">
          <exception class="java.lang.NullPointerException">
            <message>
              <![CDATA[Cannot invoke "com.VMS.PageObject.vms_MapPage.openMapPage()" because "this.Maps" is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException: Cannot invoke "com.VMS.PageObject.vms_MapPage.openMapPage()" because "this.Maps" is null
at com.VMS.TestCases.TC_MapTest.addNewMap(TC_MapTest.java:15)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addNewMap -->
        <test-method signature="addNewMapInVMS()[pri:2, instance:com.VMS.TestCases.TC_MapTest@3ec11999]" started-at="2023-07-20T18:31:17 IST" name="addNewMapInVMS" finished-at="2023-07-20T18:31:17 IST" duration-ms="1" status="FAIL">
          <exception class="java.lang.NullPointerException">
            <message>
              <![CDATA[Cannot invoke "com.VMS.PageObject.vms_MapPage.openNewMapForm()" because "this.Maps" is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException: Cannot invoke "com.VMS.PageObject.vms_MapPage.openNewMapForm()" because "this.Maps" is null
at com.VMS.TestCases.TC_MapTest.addNewMapInVMS(TC_MapTest.java:28)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addNewMapInVMS -->
      </class> <!-- com.VMS.TestCases.TC_MapTest -->
    </test> <!-- OldVMSVersionSetup(BeforeUpgrade) -->
  </suite> <!-- Suite -->
</testng-results>
